[package]
name = "StateEstimation_MEKF"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "1.0.0"
libm = "0.2"
cty = "0.2"
meshcat = "0.1.2"
nalgebra = "0.32"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }